baseURL = "https://anyicomplex.github.io/"
DefaultContentLanguage = "en" # Theme's display language, supports: en, fr, zh, zh-hant
DefaultContentLanguageInSubdir = true
LanguageName = "English"
contentDir = "content/en"
languageCode = "en-us"
title = "anyicomplex's Blog"
copyright = "2021 - 2022 © anyicomplex"
theme = "diary"
# googleAnalytics = "UA-123-45"

[languages]
  [languages.en]
    weight = 1
  [languages.zh]
    LanguageName = "简体中文"
    contentDir = "content/zh"
    languageCode = "zh-cn"
    title = "安怡的博客"
    weight = 1
    [languages.zh.params]
      title = "安怡的博客"
      subtitle = "编程与生活 | 随笔杂记"
      description = "编程与生活 | 随笔杂记"
    [languages.zh.menu]
[[languages.zh.menu.main]]
url = "/zh/categories"
name = "分类"
weight = 2
[[languages.zh.menu.main]]
url = "/zh/tags"
name = "标签"
weight = 3
[[languages.zh.menu.main]]
url = "/zh/posts"
name = "归档"
weight = 1
[[languages.zh.menu.main]]
url = "/zh/index.xml"
name = "RSS 订阅"
weight = 4
  [languages.zh-hant]
    LanguageName = "正體中文"
    contentDir = "content/zh-hant"
    languageCode = "zh-tw"
    title = "安怡的博客"
    weight = 1
    [languages.zh-hant.params]
      title = "安怡的博客"
      subtitle = "編程與生活 | 隨筆雜記"
      description = "編程與生活 | 隨筆雜記"
    [languages.zh-hant.menu]
[[languages.zh-hant.menu.main]]
url = "/zh-hant/categories"
name = "分類"
weight = 2
[[languages.zh-hant.menu.main]]
url = "/zh-hant/tags"
name = "標籤"
weight = 3
[[languages.zh-hant.menu.main]]
url = "/zh-hant/posts"
name = "歸檔"
weight = 1
[[languages.zh-hant.menu.main]]
url = "/zh-hant/index.xml"
name = "RSS 訂閱"
weight = 4

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
disableDarkMode=true
enableReadingTime = true

favicon = "https://github.com/fluidicon.png"

subtitle = "Programming and Life | Miscellaneous Essays"
enableGitalk = true

globalLicense = "CC-BY-NC 4.0"
globalLicenseLink = "https://creativecommons.org/licenses/by-nc/4.0/"

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "anyicomplex's Blog" # will set 'og:site_name'
description = "Programming and Life | Miscellaneous Essays"  # will set 'og:description'

[params.gitalk]
  owner = "anyicomplex"
  repo = "anyicomplex.github.io"
  client_id = "ecaa9e60860d0402573e"
  client_secret = "e2a72d4628c46b1d35bdeef27db30f692f731c01"
[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
url = "/en/categories"
name = "Categories"
weight = 2
[[menu.main]]
url = "/en/tags"
name = "Tags"
weight = 3
[[menu.main]]
url = "/en/posts"
name = "Archives"
weight = 1
[[menu.main]]
url = "/en/index.xml"
name = "RSS Feed"
weight = 4